language: java
jdk: oraclejdk8
before_install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: true
script:
- mvn clean install
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: elasticbeanstalk
  access_key_id: ${access_key_id}
  secret_access_key:
    secure: ${secret_access_key}
  region: us-west-2
  app: Test
  env: Test-env
  bucket_name: elasticbeanstalk-us-west-2-940338783322
env:
  global:
  - secure: oRyACopigLYmeVw9BKA13187EEGmAb6OHnDw3muXrrAuMon8aSk9/a05KcjH/wpCKvx6Sij8RoZujL0eAZPv2QqvzSXKt5swDGwYXGYwsAPy0OBeMN+BYYcKDc98Bh2KAoS+1cPw07ejWrqQNqKAvqSawhEgNGDjgtPrRtaT3JLUYvGLwjBMsgJ2YkJRW3aE1DzHKiEueoyWUq8Sld5j7VPBrpbUcHRW8ejslpQE+I6r9/fv57W3xVCTyfNG5hTEbExft/pxxR4ZORIZWwfbO3HeYd8xWhbe/ljoWvRGvoLU+QEuG+9elZHn194oIUP4Da5xVTBlwHqH7qJwnzdEX55mv6wcroJwoTTLvqLwLSsg29SVKifcE1MJaMftObu1T6yq5DlBe/m047RVYsoZ2pk57uF0ludJTiOP8U24PaNbRHq9+J3Jm/6g45D7APQgfLKInxUIYfhJRQqc8qCxaNSU1sZO+tytjppTpAZH9joJm8+EFTQe4m5nycbBT/k+Eg1Yur/9KEPU4G9ABOIS3aOZtS8uEd2Nm3e2TiP5bea8/qBcPv2jf+lyITkMBZSwpficft4vhwKMgYdYE37JHdqXQJzcEloGdDy8swJXZLiYWgWGEdl1YaUVeOv0gCnvQFDwwpSojrisi+u3qvUKyVmCWzdroFF2f147AHorfPs=
  - secure: mcALN5ZSX0zMVNssyAROZ9bUOuSQ3HMOP8Zol804fsob/a/RlQE+1wMdzqL/5LEMqq4prnnqFjVF15I9QVCyqc0NoWwCEdi0RADZK+9UKV/+yniRkh7CSRWJ2WpUDubF7m28LQ0ovY1FFCa3aaOaqleaLkK/PtN4920GnM4VlhiASRjSspbrSzIQBj4ErJR22IPB9AX3AncEI8j43enEyUGKRN2N8P1uoKFUYWSpIX92ZTi27GI5TWM80Z0uHGfRQapIZCahBiCEG78wzBKfRGmjrFTGfrc9vyX99gwnKRxIpDX+Klsmi+Vq1HJrPTSbwgh3JYBLQR3QHuIwaV8aEA0wlwhvWUFK/rkhpvpWP48YV3Ic+bDmc0JnUx90MouBGH52DXX0/RCZN7/6jCoRPUXArEI1fx0rApdAI4Ohm8f+E7jbVJCorbqXPw5/dtjVuqD4FNTlRU1ih771wzjccyX/PY48t7PpGjQAflrg80PskXRSVT5RnSwiTfDtaS+agGYWUJ/m7uX3D8hgvgoGyb2if8jodQU9D9Dj2VrV9PBTqvRnJE5J47fsbG98IAOiOfV0kGj6ewHrVO5suFK9AsRogK29uVHi2DkhkgfofbhUbQ47HjykLiVlmt0f9cufq4SwntoZFutaj3ALMITHT3XVPFqu+XTcFhKc/hwLbuo=
