language: java
jdk: oraclejdk8
before_install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: true
script:
- mvn clean install
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: elasticbeanstalk
  access_key_id: "${access_key_id}"
  secret_access_key:
    secure: "${secret_access_key}"
  region: ap-southeast-1
  app: edium-service-auth
  env: edium-service-auth-environment
  bucket_name: hienhv
env:
  global:
  - secure: FGpgUb11Q/sbnh6L6vbkhrGdv7KZnAURPZyKZRlWkGERFVISe6ipCFTG7RzqO6dW5EsOIPACBVWZgVXlE5xrnnC9HWAk2oheGY0b9ObqDTj2ofDgYBxGUXgsfbM+vvAu/K4laJ7ViQ5vzk6LtOFZdc3UeZ5+iI0P2F0ysGUH2O/5HaCkaEWYyPT1GrN+vTmFtMGvIGOHtV3WCUygICk1BcE5xF4NvLgUortO6877Z6rV2P74m3b3YQ6RO1s2mPp3+XqlGHt6A8OYKVprqWG1+DPdcq7NF/OqwUgRwQqZrBH7PupRiaf8SU8+JbiODy3Qgxx9McmfUqY+fuHO66bq0knndU33mjNghH7VjarXMmpv653pzRyoak/8ldmVco4vgJyqMP+Y+N6vscqjMhY8czS6ycSwqm8wXB2EpO+xBlhGQR+TZQ56KKIHvzwXDsD0ElIgQv8U029uCkMK/VDf6BxTcMVEzlYBPNebvbvy7RzcsxsSJxpZDu37LVLaY0FJTayUeiFYn6gnSiQC2Zk6+BYVDDDxXjTnTVfh1DImkZ9+YBFyJEC8w0NGsWv/qCK+I4CTy63qnJUTVz2LS78ksl6f0CaX++BhIA8sSQTN4mRKFW3RtxWk5DuqPvBl9HGX5wdzZ58pZ/EPlqQYzzAudRSsRYJbjjVLRG9iG9UQZvo=
  - secure: r7vXJ7Y4dGYsRpQBtFTrgB5FevnCSM44SSWpsuHLMmxXahZ2feOFylT9ioit79Z6O2nP3RarwyuBVcUu7UTvBS2ZBeeu5CMb9m/3Fjg8AegaHad2ooEENYkFxBUFjN4yQ2N72yv9HawrvGQ46xgoayhICfljGe122koh63Kj2e9PCa2Zf3/XngNQ/9DpEYmDYSXsjfKZbxukk9vXkshwJO1RZoHlvH6T36DiVcpSGABfjcKVLewsn8ZgJ1wLqa3VlfTTN5+o2t2+boEYcv9Sobu4o5LL8Ki0smmfUI8ePN49WdXFJV91UfZ5LRBJzMXSHvANR4yqoEH6p6yvWFmeoxgbbr2Ln1HyFuMGV/UR/3Jc89TU7iTjp/wp4GCwLH+rhmpBPmLZO5OCPQU0NSe6AN/+lh5f197PSQEcWl5tiqavUJMqJMsR9JVKLhaZpeRSMoJSvvOxAKo6kS4aVwX4qVBJQrZWaV1rvvTm2qT0AoeHdIl6Np9q59ggfEwWaQHCGiLLNlF3bdC7HJaezx6Lo3kuGcDzcQ7sHE/iCO6nRTB1ZW4WP/KltU+9/l8knv4gC1je7csd09Tb6FMfJ/4pQjUTYOR0H+FaNZvl77HzOFdZTGK3llN7oC/OFYm/Vic7eQEIhTNXTr1QJU9mVxTRyvFoZ9T01B37OzyRH6KEazg=
